services:
  neo4j:
    image: neo4j:latest
    volumes:
        - /$HOME/neo4j/logs:/logs
        - /$HOME/neo4j/config:/config
        - /$HOME/neo4j/data:/data
        - /$HOME/neo4j/plugins:/plugins
        - ./neo4j_import:/var/lib/neo4j/import  # Mount to the correct Neo4j import directory
    environment:
        - NEO4J_AUTH=neo4j/courtlistener
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always