version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_USER=courtlistener
      - DB_PASSWORD=postgrespassword
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=courtlistener
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=courtlistener
      - POSTGRES_USER=courtlistener
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - neo4j
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  neo4j:
    image: neo4j:latest
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./src/neo4j_import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/courtlistener
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

volumes:
  neo4j_data:
  neo4j_logs:
