version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_USER=courtlistener
      - DB_PASSWORD=postgrespassword
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=courtlistener
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=courtlistener
      - NEO4J_DATABASE=courtlistener
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - postgres
      - neo4j
    restart: always

  neo4j:
    image: neo4j:latest
    volumes:
      - neo4j_logs:/logs
      - neo4j_config:/config
      - neo4j_data:/data
      - neo4j_plugins:/plugins
      - ./src/neo4j_import:/var/lib/neo4j/import
    environment:
      - NEO4J_AUTH=neo4j/courtlistener
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

volumes:
  neo4j_logs:
  neo4j_config:
  neo4j_data:
  neo4j_plugins:
