version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    networks:
      app_net:
        ipv4_address: 192.168.0.2

    # environment:
    #   - DB_USER=courtlistener
    #   - DB_PASSWORD=postgrespassword
    #   - DB_HOST=host.docker.internal
    #   - DB_PORT=5432
    #   - DB_NAME=courtlistener
    #   - NEO4J_URI=bolt://neo4j:7687
    #   - NEO4J_USER=neo4j
    #   - NEO4J_PASSWORD=courtlistener
    #   - POSTGRES_USER=courtlistener
    #   - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - neo4j
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  neo4j:
    image: neo4j:latest
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./src/neo4j_import:/var/lib/neo4j/import
      - ./neo4j_backups:/backups
    environment:
      - NEO4J_AUTH=neo4j/courtlistener
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    networks:
      app_net:
        ipv4_address: 192.168.0.3

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel run
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: 192.168.0.4
    environment:
      - TUNNEL_TOKEN=eyJhIjoiM2Q5NzY3NDc2OTc1OTM3M2FjNThjY2I5ODFlN2E0YWYiLCJ0IjoiNGFjYTZhNDItNzA2NS00ZjY2LWFkNzYtZGY3ODdkNGYzZWU0IiwicyI6IlpUVmpPV05tWmpjdE5EYzBOaTAwWXpZMUxXSmhZMkV0TWpBME1tTmlPVEpqTW1WbCJ9
    depends_on:
      - api

volumes:
  neo4j_data:
  neo4j_logs:


networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
